### ISSUE TITLE
Nothing happens when reading Properties in YAML format from Consul

### ISSUE THREAD

**Issue by beeva-pablovaliente** [spring-cloud/spring-cloud-consul#128]
Hi, I'm trying to read a simple property written in YAML format but nothing happens during bootstrap configuration. 

Reviewing the source code (1.0.0.M5), under **ConsulPropertySource.java** at line 121, the for loop tries to extract the _props.stringPropertyNames()_, and the Enumerated returned is always empty. However, the method props.propertyNames(), returns the properties correctly, so I am not really sure why use stringPropertyNames() instead of propertyNames() in this case. Am i missing something? Or Do I have a bad configuration?

Thanks in advance.

```java
for (String propKey : props.stringPropertyNames()) {
	properties.put(propKey, props.getProperty(propKey));
}
```

My configuration in Consul is:

```
config/zuul/data = 

server:
  port: 8989
```

My boostrap.yaml for zuul is:

```yaml
spring:
  application:
    name: zuul
  profiles:
    active: loc
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
      config:
        format: YAML

```
