### ISSUE TITLE
consul not deregistering services automatically when service goes down

### ISSUE THREAD

**Issue by thangavaishnavi** [spring-cloud/spring-cloud-consul#144]
Here is my yaml configuration
```
spring:    
    cloud:
       consul:
          config:
             enabled: false
             uri: http://10.108.54.38/security-web
          discovery:
             ipAddress: http://10.108.54.38/security-web
             healthCheckPath: ${management.contextPath}
             healthCheckInterval: 15s
             address: ${management.contextPath}
    endpoints:
          shutdown:
             enabled: true
    application:
       name: security-web
       address: http://10.108.54.38/security-web
spring.cloud.consul.config.enabled: false
spring.cloud.consul.discovery.heartbeat.enabled: true
management:
    contextPath: /security-web/poll
```
