### ISSUE TITLE
Cannot Boot When Using Consul To Locate Spring Configuration Server

### ISSUE THREAD

**Issue by kurron** [spring-cloud/spring-cloud-consul#167]
I have my configuration server successfully registering in Consul when it comes up.  On the client side, however, I seem have a problem.  I get a complaint that `No qualifying bean of type [com.ecwid.consul.v1.ConsulClient] found for dependency`. I've toyed with different property settings and looked at some of the code and my guess is that `ConsulAutoConfiguration` is not creating the `ConsulClient` in time, causing the dependency issue.  Using this `bootstrap.yml`, I can trigger the error and not trip my break point in `ConsulAutoConfiguration`.

```
spring:
    application:
        name: example
    cloud:
        consul:
            enabled: true
            host: 192.168.1.227
            port: 8500
            discovery:
                enabled: true
        config:
            discovery:
                enabled: true
                serviceId: configuration-server
#            uri: ${SPRING_CONFIG_URI:http://localhost:2020}
            enabled: true
            failFast: false
```

If I set `spring.cloud.config.discovery.enabled=false`, the breakpoint fires.  I really want to avoid having to specify the location of the configuration server so any help is appreciated.
