### ISSUE TITLE
Incorrect host used for consul health check when service is running in a docker container on an overlay network

### ISSUE THREAD

**Issue by demaniak** [spring-cloud/spring-cloud-consul#192]
Good day.
Hoping this is in the right place.
In a nutshell,  I'm trying to do the following:
1. Spring Boot application, with Consul based service discovery
2. In docker containers
3. In a docker swarm
4. Using an overlay network

But, in this setup, Consul is unable to reach the health check end-points. Consul logs indicate that the hostnames used are unknown (unresolvable), like so:

```
agent: http request failed 'http://5d1690999ec3:8080/health': Get http://5d1690999ec3:8080/health: dial tcp: lookup 5d1690999ec3: no such host
```

So it looks like the consul client is registering with the container ID as hostname.
It seems that I'm hitting the interface problem describer [here](http://developerblog.info/2015/11/16/splendors-and-miseries-of-docker-network/). Maybe.

I have tried to to prevent consul from using (for example) the `docker_gwbridge` interface by adding `spring.cloud.inetutils.ignoredInterfaces=docker_gwbridge` to my `application.properties`. Also does not seem to have any effect.

How or why ever it is happening, the result is that consul ends up with an inaccessible health check URI. Attaching the consul container to the overlay network does not seem to help.
This of course then means that any Ribbon interfacing with RestTemplate is also borked.

I am honestly not sure if I'm doing something stupid, or if this is a bug or a limitation or what.

**Comment by iadknet** [comment]
You might try `spring.cloud.consul.discovery.preferIpAddress=true` . 

 If your overlay network is not reported on `eth0` (for example weave might add an `ethwe` interface, then the ignoredInterfaces might also be useful.  That is actually what led me to your issue... I was running into problems with weave and did not know about the `ignoredInterfaces` option.  Thanks!

**Comment by demaniak** [comment]
Thanks @iadknet - I will give that a try!

Btw, the `ignoredInterfaces ` docs found [here](http://projects.spring.io/spring-cloud/spring-cloud.html#ignore-network-interfaces)

**Comment by demaniak** [comment]
It feels like I'm missing something here.
So, using @iadknet 's tip of setting `spring.cloud.consul.discovery.preferIpAddress=true`, I can get a healthy service - IFF I connect the consul container to the overlay network.

But of course I can't I create an overlay network before I've created at least the consul master.
Bootstrapping then seems to become a slightly brittle process.

Is this just the way it is? AM I missing something? 
Should I perhaps NOT be using consul for swarm KV-backend AND service discovery? I could maybe look to using Eureka for service discovery instead, and leave consul and swarm to do their thing?

**Comment by spencergibb** [comment]
I can't comment on how consul and swarm work together since I've never used swarm. I know there are others that are using consul/docker together. You might try the [gitter room](https://gitter.im/spring-cloud/spring-cloud). Generally what I've seen work is telling s-c-consul what IP to advertise via an env var rather than having spring-cloud trying to guess.

**Comment by aatarasoff** [comment]
@demaniak I think you need to check all of your network interfaces. We have example with advanced configuration (our example works with eureka and with consul) https://github.com/aatarasoff/wild-microservices-in-kiev/blob/master/insurance-service/src/main/resources/application.yml

Pay attention to this configuration:
```
cloud:
    inetutils:
      ignored-interfaces:
        - vbox*
        - bridge*
        - awd*
        - lo*
        - gif*
        - stf*
        - en1
        - en2
```

**Comment by aatarasoff** [comment]
@demaniak and if you could provide your example and configuration it will be easier to help you with your problem

**Comment by demaniak** [comment]
Thank you @aatarasoff I will have a look at the examples. 

I will also provide (slightly cleaned up) config as soon as possible.
What pieces would be most relevant (between compose file, network setup, consul setup, swarm setup, all of the above?)

**Comment by aatarasoff** [comment]
@demaniak if it is not a secret project you could create new project here (on Github) and share it. If you have any scripts (e.g. compose file) it may helps

**Comment by demaniak** [comment]
@aatarasoff ah unfortunately it is a bespoke application, so I will need to sanitize a bit before posting.

**Comment by demaniak** [comment]
Below I will paste the sanitized setup scripts etc.
After [reviewing this again](http://www.smartjava.org/content/service-discovery-docker-and-consul-part-1), I'm wondering if my mistake is not in starting all the consul agents (and servers) outside the swarm from the start?

Just to recap, by forcing consul spring to use IP (and not hostname), and then connecting the consul agent which was used to register the services to the swarm network - consul is able to contact all services, and everything works as expected (Ribbon RestTemplate etc)

Anyway,here is my partial setup (I hope it is enough to troubleshoot, but not to much noise!)
First, the "infrastructure bootstrap" aimed at one data center:
```
#!/bin/bash
echo Provision the ABC swarm master in replication mode
docker-machine create --driver=generic --generic-ip-address=10.10.0.2  --generic-ssh-user=thedude --generic-ssh-key=/home/myuser/.ssh/thedude/id_rsa --engine-label funkyapp.swarm.type=master --engine-label funkyapp.discovery.type=master --engine-label funkyapp.web.frontend=false --engine-label funkyapp.site=abc --swarm --swarm-master --swarm-discovery="consul://10.10.0.2:8500" --engine-opt="cluster-store=consul://10.10.0.2:8500" --engine-opt="cluster-advertise=eth0:2376" --swarm-opt="replication=true"  abcsm

echo Switching over to abcsm...
eval $(docker-machine env abcsm)
echo
echo Create the abc consul master, it will join with XYZ
#$(docker run --rm progrium/consul cmd:run 10.10.0.2::10.11.0.11 -d)
docker run --restart always --name consul -h abcsm -v consuldata:/data  -p 10.10.0.2:8300:8300 	-p 10.10.0.2:8301:8301 	-p 10.10.0.2:8301:8301/udp 	-p 10.10.0.2:8302:8302 	-p 10.10.0.2:8302:8302/udp 	-p 10.10.0.2:8400:8400 	-p 10.10.0.2:8500:8500 	-p 172.17.0.1:53:53 	-p 172.17.0.1:53:53/udp 	-d 	progrium/consul -server -advertise 10.10.0.2 -retry-join-wan 10.11.0.11 -retry-join-wan 10.11.0.10
eval $(docker-machine env -u)
echo Done with abcsm
echo

echo Provision the DB dbnode swarm node, and join it to the swarm
docker-machine create --driver=generic --generic-ip-address=10.10.0.3  --generic-ssh-user=thedude --generic-ssh-key=/home/myuser/.ssh/thedude/id_rsa --engine-label funkyapp.swarm.type=slave --engine-label funkyapp.discovery.type=agent --engine-label funkyapp.web.frontend=false --engine-label funkyapp.storage=persists --engine-label funkyapp.site=abc --swarm  --swarm-discovery="consul://$(docker-machine ip abcsm):8500" --engine-opt="cluster-store=consul://$(docker-machine ip abcsm):8500" --engine-opt="cluster-advertise=eth0:2376"  dbnode

eval $(docker-machine env dbnode)
echo Create consul client on dbnode, it will join with ABC master
docker run --restart always --name consul -h dbnode  -p 10.10.0.3:8300:8300 	-p 10.10.0.3:8301:8301 	-p 10.10.0.3:8301:8301/udp 	-p 10.10.0.3:8302:8302 	-p 10.10.0.3:8302:8302/udp 	-p 10.10.0.3:8400:8400 	-p 10.10.0.3:8500:8500 	-p 172.17.0.1:53:53 	-p 172.17.0.1:53:53/udp 	-d 	progrium/consul  -advertise 10.10.0.3 -join 10.10.0.2
eval $(docker-machine env -u)
echo Done with dbnode
echo

echo Provision "app node" node and join to node0 swarm node
docker-machine create --driver=generic --generic-ip-address=10.10.0.1  --generic-ssh-user=thedude --generic-ssh-key=/home/myuser/.ssh/thedude/id_rsa --engine-label funkyapp.swarm.type=slave --engine-label funkyapp.discovery.type=agent --engine-label funkyapp.web.frontend=true --engine-label funkyapp.site=abc --swarm  --swarm-discovery="consul://$(docker-machine ip abcsm):8500" --engine-opt="cluster-store=consul://$(docker-machine ip abcsm):8500" --engine-opt="cluster-advertise=eth0:2376"  node0

echo
echo Switch to node0
eval $(docker-machine env node0)
echo Setup consul client agent on node0
docker run --restart always --name consul -h node0 -p 10.10.0.1:8300:8300 	-p 10.10.0.1:8301:8301 	-p 10.10.0.1:8301:8301/udp 	-p 10.10.0.1:8302:8302 	-p 10.10.0.1:8302:8302/udp 	-p 10.10.0.1:8400:8400 	-p 10.10.0.1:8500:8500 	-p 172.17.0.1:53:53 	-p 172.17.0.1:53:53/udp 	-d 	progrium/consul  -advertise 10.10.0.1 -join 10.10.0.2
eval $(docker-machine env -u)
echo Done with node0
echo

echo
echo Provision and join the "repo node" reponode swarm node
docker-machine create --driver=generic --generic-ip-address=10.10.0.4  --generic-ssh-user=thedude --generic-ssh-key=/home/myuser/.ssh/thedude/id_rsa --engine-label funkyapp.swarm.type=slave --engine-label funkyapp.discovery.type=agent --engine-label funkyapp.web.frontend=false --engine-label funkyapp.repo=true --engine-label funkyapp.site=abc --swarm  --swarm-discovery="consul://$(docker-machine ip abcsm):8500" --engine-opt="cluster-store=consul://$(docker-machine ip abcsm):8500" --engine-opt="cluster-advertise=eth0:2376"  reponode
eval $(docker-machine env reponode)
echo Setup consul client agent on reponode
docker run --restart always --name consul -h reponode -p 10.10.0.4:8300:8300 	-p 10.10.0.4:8301:8301 	-p 10.10.0.4:8301:8301/udp 	-p 10.10.0.4:8302:8302 	-p 10.10.0.4:8302:8302/udp 	-p 10.10.0.4:8400:8400 	-p 10.10.0.4:8500:8500 	-p 172.17.0.1:53:53 	-p 172.17.0.1:53:53/udp 	-d 	progrium/consul  -advertise 10.10.0.4 -join 10.10.0.2
eval $(docker-machine env -u)
echo Done with reponode
echo

echo Setting up BLUE overlay network
eval $(docker-machine env --swarm abcsm)
docker network create --driver overlay --subnet=10.9.0.0/16 blue-net
eval $(docker-machine env -u)
echo


```

Next, main compose file:
```
version: '2'
services:
 web:
  image: private-reg.mycompany.com/funkyapp-web
  ports:
     - "8080:8080"
  restart: on-failure
  environment:
    - spring.profiles.active=prod
    - "constraint:funkyapp.web.frontend==true"

  logging:
     driver: json-file
     options:
       max-size: "2m"
       max-file: "40"
       labels: "web"

 widget-api:
  image: private-reg.mycompany.com/funkyapp-widget-api
  expose:
   - "8080"
  restart: on-failure
  environment:
   - spring.profiles.active=prod
  logging:
     driver: json-file
     options:
       max-size: "2m"
       max-file: "40"
       labels: "widget-api"

 payment-api:
  image: private-reg.mycompany.com/funkyapp-payment-api
  expose:
   - "8080"
  restart: on-failure
  environment:
    - spring.profiles.active=prod
  logging:
     driver: json-file
     options:
       max-size: "2m"
       max-file: "40"
       labels: "payment-api"

 auth:
  image: private-reg.mycompany.com/funkyapp-auth
  expose:
   - "8080"
  depends_on:
    - "auth-store"
  restart: on-failure
  environment:
   - spring.profiles.active=prod
  logging:
     driver: json-file
     options:
       max-size: "2m"
       max-file: "40"
       labels: "auth"

 auth-store:
   image: postgres
   restart: on-failure
   environment:
     - POSTGRES_PASSWORD=ldjfslkj3454543tfdf
     - "constraint:funkyapp.storage==persists"
   volumes:
     - auth-db-data:/var/lib/postgresql/data/

 gizmos:
   image: private-reg.mycompany.com/funkyapp-gizmos
   expose:
      - "8080"
   restart: on-failure
   privileged: true
   environment:
     - spring.profiles.active=prod
   logging:
     driver: json-file
     options:
       max-size: "2m"
       max-file: "40"
       labels: dcc3

 the-important-api:
   image: private-reg.mycompany.com/the-important-api
   expose:
    - "8080"
   restart: on-failure
   privileged: true
   environment:
     - spring.profiles.active=prod
   logging:
    driver: json-file
    options:
      max-size: "2m"
      max-file: "40"
      labels: thales


volumes:
  auth-db-data:
    driver: local

networks:
  default:
    external:
      name: blue-net

```

Finally a override compose file for production:
```
version: '2'
services:
 web:
  extra_hosts:
    - "discovery:10.10.0.2"
  environment:
    - spring.cloud.consul.host=discovery
```
