### ISSUE TITLE
No interpolation on spring.cloud.consul.discovery.healthCheckPath

### ISSUE THREAD

**Issue by ssouris** [spring-cloud/spring-cloud-consul#199]
Based on the documentation I should be able to set a custom health check path.

```
# Example bootstrap.properties
spring:
  application:
    name: testConsulApp
  cloud:
    consul:
      discovery:
        healthCheckPath: ${management.contextPath}/health
```

This does not seem to work and by checking the code I found that no interpolation is done on that property.

Thanks in advance
