### ISSUE TITLE
How to remove services using unique IDs

### ISSUE THREAD

**Issue by nickcodefresh** [spring-cloud/spring-cloud-consul#222]
Hi,

Our services have been configured to use unique service IDs as advised in http://cloud.spring.io/spring-cloud-static/spring-cloud.html#spring-cloud-consul-retry:

```
spring:
  cloud:
    consul:
      discovery:
        instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
```

What we're finding is that when services are restarted, the old version hangs around in Consul for ever:

![consul by hashicorp](https://cloud.githubusercontent.com/assets/5837418/18509435/890b8b94-7a70-11e6-8fb4-55faf5e663a6.png)

Is there anyway to delete these, or must we switch to having non-unique IDs per instance?

Thanks

Nick
