### ISSUE TITLE
instanceId with ${random.value} causes new instanceId that consul is unaware of on refresh

### ISSUE THREAD

**Issue by sokie** [spring-cloud/spring-cloud-consul#227]
When using `spring-cloud-consul-config` , updating/adding a key to the kv store, causes a propagation that refreshes the default properties as well.
This causes problems if using properties like:
```
spring:
  cloud:
    consul:
      discovery:
        instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
```
In our case, instanceId will get generated again and cause problems with consul.
[this](https://github.com/spring-cloud/spring-cloud-consul/blob/v1.1.0.RC1/spring-cloud-consul-discovery/src/main/java/org/springframework/cloud/consul/discovery/ConsulDiscoveryClient.java#L76) will return null since it will try to find a service with the newly generated instanceId.
InstanceId should not be refreshed.
