### ISSUE TITLE
When configuring hearbeat check it is not adding the HTTP check

### ISSUE THREAD

**Issue by ezraroi** [spring-cloud/spring-cloud-consul#242]
The following configuration will only add a ttl check and not 2 checks: http and ttl

```yml
spring:
    application:
        index: \${random.int}
    sleuth:
        sampler:
            percentage: 0.1
    cloud:
        consul:
            host: itstl068.iil.intel.com
            port: 8500
            discovery:
                healthCheckPath: \${management.context-path}/health
                heartbit:
                    enabled: true
                management-suffix: manage
```
