### ISSUE TITLE
Unable to register healthcheck if spring.cloud.consul.discovery.port property is set

### ISSUE THREAD

**Issue by petrkarel** [spring-cloud/spring-cloud-consul#281]
It's impossible to register a new service with healthcheck if `spring.cloud.consul.discovery.port` property is set. Service is registered fine but without check. My spring boot application (service) run in docker container (bridge mode) with random external port managed by Mesos. The port inside container is set to 8080. The service is registered to Consul Service Registry with external IP and PORT with properties `spring.cloud.consul.discovery.ip-address` and `spring.cloud.consul.discovery.port`. Everything works as expected except healthcheck. If I comment out the `spring.cloud.consul.discovery.port` property - healthcheck is registered but with port 8080. I solved my problem with overriding `org.springframework.cloud.consul.serviceregistry.ConsulAutoRegistration` class where I modified  registration() method: 

```
public static ConsulAutoRegistration registration(ConsulDiscoveryProperties properties, ApplicationContext context, ServletContext servletContext, HeartbeatProperties heartbeatProperties) {
...
   if (properties.getPort() != null) {
     service.setPort(properties.getPort());
     setCheck(service, properties, context, heartbeatProperties);
   }
...

}
```

After that everything works fine. I'd like to ask you if I missed something in configuration.

Snippet of my bootstrap.yml:

```
spring:
  cloud:
    consul:
      host: ${HOST} #enviroment property
      port: 8500
      discovery:
        enabled: true
        register: true
        prefer-ip-address: true
        ip-address: ${HOST} #enviroment property
        port: ${PORT} #enviroment property
        register-health-check: true
        health-check-critical-timeout: 5m
server:
  port: 8080
```

Thank you very much.

Regards,
Peter
