### ISSUE TITLE
Can not register service to consul while packaging as war file

### ISSUE THREAD

**Issue by overstart** [spring-cloud/spring-cloud-consul#313]
My maven dependency version like below:
```xml
<spring.version>4.3.8.RELEASE</spring.version>
<spring.boot.version>1.5.3.RELEASE</spring.boot.version>
<spring.boot.version>1.5.3.RELEASE</spring.boot.version>
<spring.cloud.version>Dalston.RELEASE</spring.cloud.version>
<spring.cloud.consul.version>1.2.0.RELEASE</spring.cloud.consul.version>
```

My Application class like below:
```java
@EnableDiscoveryClient
@SpringBootApplication
@MapperScan(basePackages = "td.item.mapper")
public class Application extends SpringBootServletInitializer{

    protected static Logger logger = LoggerFactory.getLogger(Application.class);

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
        RuntimeMXBean runtimeMxBean = ManagementFactory.getRuntimeMXBean();
        List<String> arguments = runtimeMxBean.getInputArguments();
        logger.info("jvm args: " + arguments);
    }

    @Override
    protected SpringApplicationBuilder configure(SpringApplicationBuilder builder) {
        return builder.sources(Application.class);
    }
}
```
and my bootstrap.yml like this:
```yml
spring:
  application:
    name: td-service-item
  cloud:
    consul:
      discovery:
        health-check-path: ${management.context-path}/health
        health-check-interval: 15s
        instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
        tags: qa
        prefer-ip-address: true
      host: 127.0.0.1
      port: 8500
      config:
        enabled: true
        watch:
          enabled: true
```

When i run this application on the embedded tomcat  it works fine. but when i packaging this as a war file and run on an external tomcat , it doesn't register the service to consul. 

Is there any way to work around this problem?
Thanks
