### ISSUE TITLE
Https support for health checks

### ISSUE THREAD

**Issue by Binary00** [spring-cloud/spring-cloud-consul#33]
It appears there are a couple options for health check support.  A full health check URL and a URL auto generated based on environment settings.  

Is there a way to have the health check URL use https without having to set the full url in configuration? 

I've gleamed from the class below of the two options, but didn't know if there were others? 

ConsulLifecycle.java::74 :
```java
if (properties.getHealthCheckUrl() != null) {
  check.setHttp(properties.getHealthCheckUrl());
} else {
  check.setHttp(String.format("http://%s:%s%s", properties.getHostname(),
    service.getPort(), properties.getHealthCheckPath()));
}
```

Currently we have an application that is all https, but since the auto generated URL is http, the health check fails. Didn't know if I was missing something. 

So I found another solution, not sure it would be optimal, but maybe it's the intended way of using `healthCheckUrl`.  Just use Spring's filtering to get `HOSTNAME` and `server.port` at application startup. 
(This dawned on me while writing up this issue)

```yml
spring:
  application:
    name: app_name
  cloud:
    config:
      uri: https://config.url:port
    consul:
      discovery:
        healthCheckUrl: https://${HOSTNAME}:${server.port}/health
```

Thanks!
