### ISSUE TITLE
spring-cloud-consul config pick up the wrong consul host on "fresh" operation

### ISSUE THREAD

**Issue by GeekDaniel** [spring-cloud/spring-cloud-consul#340]
I used a consul which started up on the other machine. So I customed 'spring.cloud.consul.host'. It's wired to pick up  the wrong consul host on "fresh" operation after the app start up correctly.

Here is my bootstrap.yml
```
server:
  port: 8090
spring:
  profiles:
    active: master
  application:
      name: consulclient
  cloud:
    config:
            enabled: false
    consul:
      config:
        enabled: true
        format: YAML
        data-key: master/consulclient-master.yml
        acl-token:
        prefix: config
      host: 192.168.141.130
      port: 8500
      enabled: true
      discovery:
        enabled: true
        instanceId: ${spring.application.name}-${spring.cloud.consul.host}-${spring.cloud.consul.port}
        serviecName: ${spring.application.name}
        health-check-interval: 5s
        healthCheckPath: /health
        preferIpAddress: true
management :
  security:
    enabled: false
```
Here is the console error message:

```
2017-08-02 18:26:55.686 ERROR 79140 --- [nio-8090-exec-7] o.s.boot.SpringApplication               : Application startup failed
com.ecwid.consul.transport.TransportException: org.apache.http.conn.HttpHostConnectException: Connect to localhost:8500 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused: connect
```
Why the app goes for localhost/127.0.0.1 during "refresh" operation ?
