### ISSUE TITLE
Service did not re-register with consul after a failed healthcheck removed it from the pool.

### ISSUE THREAD

**Issue by titoc** [spring-cloud/spring-cloud-consul#358]
The mongodb that my service was using went down abruptly. Consequently the health check timeout of 15s was over. So consul removed the service from the pool. But then the service reconnected with mongodb after sometime. but it did not re-register with consul. 

I thought the service would re-register itself back as healthy in consul which it did not.  Am I missing anything in my configuration or is it how its designed to work ?

```
spring:
  profiles: dev
  application:
    name: deployed-service
  cloud:
    consul:
      enabled: true
      discovery:
        prefer-ip-address: true
        instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
        health-check-critical-timeout: 15s          
    config:
      enabled: false
```
