### ISSUE TITLE
2-way TLS throwing bad cert on consul

### ISSUE THREAD

**Issue by sonicsandy** [spring-cloud/spring-cloud-consul#361]
Hi 

I have **Consul (0.9.3)** as a service/discovery utility for the spring boot micro-services. I was able to enable TLS 1-way, i.e. consul -> microservice.

### For that, my consul.json reads:
```
{
	"ca_file": "C:\\ca.cer",
	"verify_outgoing": true
}
```

### Spring boot configuration reads:
```
server: 
  port: 443
  ssl:
    key-store: C:\spring.p12
    key-store-password: changeit
    key-store-type: JKS
```

_The above works well._ 
But the moment I try the 2-way, it gives me **bad cert on consul logs, empty chain at spring boot** application logs. Here is the configuration:

### consul.json
```
{
	"ca_file": "C:\\ca.cer",
	"verify_outgoing": true,
	**"cert_file": "C:\\consul.cer",
        "key_file": "C:\\consul.key",
	"verify_incoming": true**
}
```

### application.yml on spring boot app.
```
server: 
  port: 443
  ssl:
    key-store: C:\spring.p12
    key-store-password: changeit
    key-store-type: JKS
    **trust-store: C:\spring-ts.p12
    trust-store-password: changeit
    trust-store-type: JKS
    client-auth: NEED
    enabled: true**
```

Any reason why the consul agent is not able to pass the certs to the server?
