### ISSUE TITLE
Can Consul be used for Configuration only

### ISSUE THREAD

**Issue by alexg72** [spring-cloud/spring-cloud-consul#364]
I would like to use **spring-cloud-starter-kubernetes-all** for discovery and consul **spring-cloud-starter-consul-config** for retrieving configuration properties like:

@Value("${testValue}")
String testValue; 

Reason:
Consul provides a nice UI to maintain KV and it is very easy to change. 
Also Consul Vault can be used to manage secrets.

Please let me know if it possible. My test is failing.

Thank you,
Alex

**Comment by spencergibb** [comment]
Of course, it is possible, you've provided no information that will help us determine if it is a bug or not.

**Comment by alexg72** [comment]
Thank you for feedback. I was able to retrieve Consul configuration from OpenShift app.
 However, app on /health endpoint shows all applications registered with consul. 
```
"consul": {
    "status": "UP",
    "services": {
      "consul": [
        
      ],
      "helloworldclient@sha256-8080": [
        
      ],
      "helloworldclient@sha256-8443": [
        
      ],
      "helloworldclient@sha256-8778": [
        
      ],
      "helloworldserverlocal@sha256-8080": [
        
      ],
      "helloworldserverlocal@sha256-8443": [
        
      ],
      "helloworldserverlocal@sha256-8778": [
        
      ]
  }
}
```
Is there any way to disable it?
Here is my bootstrap.yml
```
spring:
  application:
    name: helloworldclient
  profiles:
    active: dev
  cloud:
    consul:
      host: xxxxxx
      port: 8500
      enabled: true
      config:
        enabled: true
      discovery:
        register: false
    kubernetes:
      config:
        enabled: false
```

Thank you,
Alex
