### ISSUE TITLE
How to configure the contextPath of service from consul?

### ISSUE THREAD

**Issue by TonyLiu0112** [spring-cloud/spring-cloud-consul#376]
I use consul as the registration center, and when my client wants to get an instance via consul, I can not seem to get the contextPath.

#### config of server

``` yml
server:
  context-path: bw-svr-advisor
spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        port: ${server.port}
        health-check-path: /${server.context-path}/health
        health-check-interval: 15s
```

When the server started, consul status was `passing`. the tags of consul show me `contextPath=/bw-svr-advisor`

### config of client

``` yml
spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        port: ${server.port}
```

``` java
@Bean
@LoadBalanced
public RestTemplate restTemplate() {
    return new RestTemplate();
}
```

When I use RestTemplate to request service, there is no contextPath in the request url. It looks like:
```
http://localhost:8080/test
```

But I expect

```
http://localhost:8080/bw-svr-advisor/test
```

How do I configure it? Thank you!
