### ISSUE TITLE
Use service discovery to configure OAuth server location

### ISSUE THREAD

**Issue by kmejka** [spring-cloud/spring-cloud-consul#421]
Hi,

As the title says, I would like to configure the location of my spring oauth server in client apps using service discovery, preferably using consul.
Something like this:

```
security:
  oauth2:
    client:
      access-token-uri: http://<service-id>/oauth/token
```

I couldn't find this in any tutorial, usually it's just something like http://localhost:8080. Is it actually possible?
I know that this might not be the best place to ask this question, but I was directed here from the spring-security-oauth project, [relevant issue here](https://github.com/spring-projects/spring-security-oauth/issues/1356)
Thanks in advance
