### ISSUE TITLE
Query matching service list based on service name and custom tag in consul

### ISSUE THREAD

**Issue by xiaoxing598** [spring-cloud/spring-cloud-consul#474]
I need to filter the list of services by service name and custom tags in Consul. How do I customize the query rules? Or does the Ribbon itself support this need?

**Comment by somejavadev** [comment]
@xiaoxing598, Did you manage to find an answer to this question? I am quite keen to do this myself.

**Comment by xiaoxing598** [comment]
@somejavadev I am also waiting for the Spring official to solve this problem, I hope they add this feature in the new version.

**Comment by OlgaMaciaszek** [comment]
The `spring.cloud.consul.discovery.server-list-query-tags` can be used for that.

Here is a usage example:
```yml
spring:
  cloud:
    consul:
      discovery:
        server-list-query-tags:
          serviceId: tag
```
Just set the desired `serviceId` and `tag` there.

@xiaoxing598 @somejavadev Does this solve your issue?
