### ISSUE TITLE
Consul Service Discovery - unable to configure consul host/port

### ISSUE THREAD

**Issue by arun0009** [spring-cloud/spring-cloud-consul#49]
I'm using Spring Boot Web Starter 1.2.4.RELEASE/1.3.0.M1 with Consul 1.0.0.M1 (with consul config). I am able to configure consul host/port in registry using the below configuration in bootstrap.yml 
```
cloud:
    consul:
      config:
        host: 127.0.0.1
        port: 8500
```
However, when I'm trying to write a client and change consul host port using the same above configurations in bootstrap.yml it doesn't seem to be picking it up. It still looks for consul at localhost:8500
