### ISSUE TITLE
Consul goroutines overwhelmed

### ISSUE THREAD

**Issue by jacobomarquis** [spring-cloud/spring-cloud-consul#549]
We enabled Consul Service Discovery and Spring starts opening connections to the Consul Server never closing and exhausting available connections. We dont see anything special on the logs, but on the systems side (using netstat) we see a 500+ "ESTABLISED" connections from the Spring microservice. 

Any ideas?

Thanks in advance

**Comment by spencergibb** [comment]
No, unfortunately. Any more information you can provide? Versions? Configuration?

**Comment by jacobomarquis** [comment]
spring:
  cloud:
    discovery:
      enabled: true
    consul:
      enabled: true
      host: ${consul_host:https://consul.cloud.housers.io}
      port: ${consul_port:8500}
      discovery:
        enabled: false
        register: false
        instance-id: ${spring.application.name}:${random.value}
#        catalog-services-watch-delay: 60000
#        catalog-services-watch-timeout: 10
        scheme: https
      tls:
        key-store-instance-type: ${kstore_instance_type}
        key-store-path: ${kstore_path}
        key-store-password: ${kstore_password}
        certificate-path: ${cert_path}
        certificate-password: ${cert_password}

**Comment by jacobomarquis** [comment]
We observed this happening in Spring 1 and Spring 2.
This is our config:
```
spring:
  cloud:
    discovery:
      enabled: true
    consul:
      enabled: true
      host: ${consul_host:https://consul}
      port: ${consul_port:8500}
      discovery:
        enabled: true
        register: false
        instance-id: ${spring.application.name}:${random.value}
        catalog-services-watch-delay: 60000
        catalog-services-watch-timeout: 10
        scheme: https
      tls:
        key-store-instance-type: ${kstore_instance_type}
        key-store-path: ${kstore_path}
        key-store-password: ${kstore_password}
        certificate-path: ${cert_path}
        certificate-password: ${cert_password}
```
All Spring services are running inside an Alpine:3.8 + Java 8 docker container image.

Consul server is running in the Docker Host and accessed through its private IP (not docker network IP)
