### ISSUE TITLE
Management service address differs

### ISSUE THREAD

**Issue by stoimen01** [spring-cloud/spring-cloud-consul#597]
We are using the latest version of spring-cloud-consul (2.2.0) and we are running our server in docker. 

Our config looks like:

**bootstrap.yml**
```
spring:
  application:
    name: app-name
  cloud:
    consul:
      enabled: ${CONSUL_ENABLED:false}
      host: consul
      port: 8500
      discovery:
        enabled: true
        fail-fast: false
        instanceId: ${spring.application.name}:${random.value}
        prefer-ip-address: true
        prefer-agent-address: true
        acl-token: ${CONSUL_TOKEN}
      config:
        enabled: false
        fail-fast: false
        acl-token: ${CONSUL_TOKEN}

management:
    server:
      port: 5001
```

We are not able to use docker in host mode, but we are able to configure consul to use the host IP by querying EC2 for it. This is why we want to use the agent address.

Everything works fine but spring-cloud-consul registers the management service with the docker IP instead of the agent IP.
Here are the logs from the app:

```
Registering service with consul: NewService{id='app-name-70f3c70d62244a4b86e99002c4475b40', name='app-name, tags=[secure=false], address='null', meta=null, port=5000, enableTagOverride=null, check=Check{script='null', interval='10s', ttl='null', http='http://172.17.0.4:5001/actuator/health', method='null', header={}, tcp='null', timeout='null', deregisterCriticalServiceAfter='null', tlsSkipVerify=null, status='null'}, checks=null}
Registering service with consul: NewService{id='app-name-70f3c70d62244a4b86e99002c4475b40-management', name='app-name-management', tags=[management], address='172.17.0.4', meta=null, port=5001, enableTagOverride=null, check=Check{script='null', interval='10s', ttl='null', http='http://172.17.0.4:5001/actuator/health', method='null', header={}, tcp='null', timeout='null', deregisterCriticalServiceAfter='null', tlsSkipVerify=null, status='null'}, checks=null}
```

As you can see the address for the management service is different. (for the app it doesn't seem to be assigned when the message is logged and it's null).

I couldn't find documentation how to have the same address for both services. Please excuse me if this problem has been already mentioned in a question or in another issue.

**Comment by stoimen01** [comment]
For anyone experiencing the same problem we were able to solve it by setting the management address to null. We would be happy to know if there is a better way of doing this though.

```
    @Bean
    public ConsulManagementRegistrationCustomizer managementRegistrationCustomizer() {

        return managementRegistration -> {
            var service = managementRegistration.getService();
            service.setAddress(null);
        };
    }
```

**Comment by spencergibb** [comment]
The hostname defaults to an attempt to locate the local ip and host. See the docs for ignoring docker networks https://cloud.spring.io/spring-cloud-static/spring-cloud-commons/2.2.0.RELEASE/reference/html/#ignore-network-interfaces. Otherwise your solution is fine.

**Comment by stoimen01** [comment]
I am afraid that ignoring the network interfaces won't work because in our case only the docker and loopback addresses are visible from inside the container. I just did a quick experiment by running the following code in `jshell` inside one of our containers : 

```
var networks = NetworkInterface.getNetworkInterfaces()
Collections.list(networks)
.stream()
.flatMap(NetworkInterface::inetAddresses)
.forEach(System.out::println)
```
And it seems to print only the loopback and docker addresses:
/172.17.0.4
/127.0.0.1

**Comment by spencergibb** [comment]
We use the same logic for the service as well. You'll need to provide a mapping from an environment variable to `spring.cloud.consul.discovery.{hostname|ip-address}` or set `spring.cloud.consul.discovery.preferIpAddress=true` if that works.

**Comment by lingjiaju** [comment]
I  have a similar issue.
One service is registered as two.

```
server:
  port: 8000
  servlet:
    context-path: /manage
management:
  server:
    port: 9000
  endpoints:
    web:
      exposure:
        include: health
spring:
  cloud:
    consul:
      host: 10.0.1.18
      port: 8500
      discovery:
        prefer-ip-address: true
        instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
        health-check-path: /actuator/health
        health-check-interval: 10s
        acl-token: ${CONSUL_TOKEN}
        register: true
        deregister: false
        default-query-tag: manage-dev
        tags: manage-dev
        enabled: true
```

<img width="414" height="170" alt="Image" src="https://github.com/user-attachments/assets/bb70bd4d-c322-4073-848b-27a4cdf4ee1b" />

```
Registering service with consul: NewService{id='manage-gateway-172-20-10-2-8000', name='manage-gateway', tags=[manage-dev], address='172.20.10.2', meta={secure=false}, port=8000, enableTagOverride=null, check=Check{script='null', dockerContainerID='null', shell='null', interval='10s', ttl='null', http='http://172.20.10.2:9000/actuator/health', method='null', header={}, tcp='null', timeout='null', deregisterCriticalServiceAfter='null', tlsSkipVerify=null, status='null', grpc='null', grpcUseTLS=null}, checks=null}
Registering service with consul: NewService{id='manage-gateway-172-20-10-2-8000-management', name='manage-gateway-management', tags=[management], address='172.20.10.2', meta=null, port=9000, enableTagOverride=null, check=Check{script='null', dockerContainerID='null', shell='null', interval='10s', ttl='null', http='http://172.20.10.2:9000/actuator/health', method='null', header={}, tcp='null', timeout='null', deregisterCriticalServiceAfter='null', tlsSkipVerify=null, status='null', grpc='null', grpcUseTLS=null}, checks=null}
```
