### ISSUE TITLE
configuration about consul config

### ISSUE THREAD

**Issue by donald2008** [spring-cloud/spring-cloud-consul#621]
**Describe the bug**
I want to user consul config instead of cloud config . but it seemed not flexible. 

**Sample**
there is a yml configuration:
```

application:
  name: myTest
spring:
  cloud:
    consul:
      config:
        enabled: true
        format: yaml
        prefix: config/local
        data-key: data
```
maybe you have two requests to consul like:

> http://localhost:8500/v1/kv/config/local/myTest/?recurse&token=blablabla

if i config data2 in myTest/ and the response like this:
```
[
{
"LockIndex": 0,
"Key": "config/local/myTest/data",
"Flags": 0,
"Value": "dGVzdDogdGVzdA==",
"CreateIndex": 949,
"ModifyIndex": 949
},
{
"LockIndex": 0,
"Key": "config/local/myTest/data2",
"Flags": 0,
"Value": "dGVzdDI6IHRlc3Qy",
"CreateIndex": 1091,
"ModifyIndex": 1091
}
]
```
how can i active both data and data2?

ps: this is you how to handle data-key in ``org.springframework.cloud.consul.config.ConsulPropertySource``:

```
for (GetValue getValue : values) {
			String key = getValue.getKey().replace(this.context, "");
			if (this.configProperties.getDataKey().equals(key)) {
				parseValue(getValue, format);
			}
		}

```
