### ISSUE TITLE
Load Balancer adding scheme to service URL twice

### ISSUE THREAD

**Issue by liammacisaac** [spring-cloud/spring-cloud-consul#622]
**Describe the bug**
When using consul service discovery with spring cloud gateway, I'm experiencing an issue where the resolved service URL has the scheme defined twice. Given the trivial example below, using the URL http://localhost:8080/services/sample-service/sample/hello should proxy through to http://localhost:43808/sample/hello. However, it responds with a 500 internal server error because the URL is resolved to "http://http://localhost:43808/sample/hello".

On further examination, the root of the issue seems to be in "org.springframework.cloud.consul.discovery.ConsulServerUtils" which resolves the host name from a _HealthService_ instance. In this case, _server.getAddress()_ is "http://localhost". The catch block in line 67 indicates that this can't be parsed as an IPv6 address and therefore, "http://localhost" makes its way into the "host" field of the "Server" object. At some point further up the stack, the scheme "http://" gets concatenated onto the front of this.

**Sample**
POM file:

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.2.5.RELEASE</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>
    <groupId>XXXXXXXX</groupId>
    <artifactId>XXXXXXXX</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>spring-cloud-gateway-demo</name>

    <properties>
        <java.version>1.8</java.version>
        <spring-cloud.version>Hoxton.SR1</spring-cloud.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-gateway</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-consul-all</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
    </dependencies>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

</project>
```

and application.yml

```
spring:
  application:
      name: api-gateway
  cloud:
    consul:
      discovery:
        register: false
        registerHealthCheck: false
        tags: zone=zone1
        instanceId: ${spring.application.name}:${random.value}
    gateway:
        discovery:
            locator:
                enabled: true
        routes:
            - id: sample-service
              uri: lb://sample-service
              predicates:
                  - Path=/services/sample-service/**
              filters:
                  - RewritePath=/services/sample-service/(?<path>.*), /$\{path}
server:  
  port: ${PORT:8080}
  
logging:
    level:
        root: TRACE
```
