### ISSUE TITLE
[2020-1.M1 Regression] configserver's bootstrap.yml requires "tags: secure=true" to be discovered as secure

### ISSUE THREAD

**Issue by juergenzimmermann** [spring-cloud/spring-cloud-consul#632]
After upgrading _Spring Cloud Consul_ from _Hoxton.SR3_ to _2020-1.M1_ I had to add `spring.cloud.consul.discovery.tags: secure=true` to the configserver's bootstrap.yml so that it can be correctly discovered by other services.

**Comment by spencergibb** [comment]
Can you explain a bit more how it is required by other services? 2020-1 is a pre-release that removed tags as metadata. `secure=true` now is automatically set in `spring.cloud.consul.discovery.metadata`. https://github.com/spring-cloud/spring-cloud-consul/blob/master/docs/src/main/asciidoc/spring-cloud-consul.adoc#metadata

**Comment by juergenzimmermann** [comment]
I have a _Consul server_, and also a _config server_ as a Consul client. The config server is running with _HTTPS_ and is registered at the Consul server. In `application.yml`  of the config server I have these lines:

```
spring:
  application:
    name: config
  cloud:
    config.server.git.uri: ...
    consul:
      discovery:
        health-check-interval: 300s
        health-check-tls-skip-verify: true
        scheme: https
        # workaround for clients of the config server which is running with HTTPS
        tags: secure=true
```

Without the `tags` property the other Consul (discovery) clients are getting a URI starting with `http://` when they want to discover the URI of the config server to obtain their configurations. But they need a URI starting with `https://` because the config server is running with _HTTPS_.

@spencergibb Do you now understand my environment and the problem?
