### ISSUE TITLE
Consul tags are used as Spring Cloud metadata while Consul metadata is ignored in include-expression

### ISSUE THREAD

**Issue by deftdawg** [spring-cloud/spring-cloud-consul#678]
**Describe the bug**

spring.cloud.consul.discovery.metadata in services is ignored by spring.cloud.gateway.include-expression which instead uses tags as metadata.

I don't know if the behaviour is intentional, but is incredible confusing and goes against all of limited examples([1](https://github.com/spring-cloud/spring-cloud-gateway/issues/185),[2](https://github.com/spring-cloud/spring-cloud-gateway/blob/master/spring-cloud-gateway-server/src/test/java/org/springframework/cloud/gateway/discovery/DiscoveryClientRouteDefinitionLocatorTests.java#L50))  of how to do route filtering with `include-expression` in scg.

If nothing else, this issue can serve as some documentation for others who are searching to understand how they can restrict routes using metadata without needing to purchase Consul Enterprise to get access to Namespaces.

**Sample**

Configure the spring cloud gateway to use `include-expression: metadata['edge'] == 'true'` to include service routes that have metadata key value pair of "edge","true".

```yaml
spring:
    application:
        name: api-gateway
    cloud:
        consul:
            host: 192.168.1.100
            port: 8500
            discovery:
                instanceId: ${spring.application.name}:${random.value}

        # Basic gateway service mapping
        gateway:
            discovery:
                locator:
                  enabled: true
                  include-expression: metadata['edge'] == 'true' 
                predicates:
                  - name: Path
                    args:
                      pattern: "'/api/' + serviceId + '/**'"
                  filters:
                  - name: RewritePath
                    args:
                      regexp: "'/api/' + serviceId + '/(?<remaining>.*)'"
                      replacement: "'/${remaining}'"
```

The obvious thing to do is to send some metadata that says "edge" is "true" as part of service registration with consul....  

```yaml
spring:
    application:
        name: webservice
        consul:
            host: 192.168.1.100
            port: 8500
            config:
                enabled: true
                format: YAML
            discovery:
                instanceId: ${spring.application.name}:${random.value}
                metadata: 
                     edge: true
```

However, this DOES NOT WORK.  The metadata is registered and present in the service configuration, but the gateway does not recognize this as a service matching the `include-expression`.

We must replace this:
```yaml
                metadata: # Doesn't work with scg include-expression
                     edge: true
```
with this:
```yaml
                tags: edge=true # this WORKS
```

Consul service **tags** are being used as metadata by scg for the purpose of evaluating include-expression.
