### ISSUE TITLE
`spring.cloud.consul.discovery.server-list-query-tags` is ignored when using Spring Cloud LoadBalancer

### ISSUE THREAD

**Issue by mario45211** [spring-cloud/spring-cloud-consul#680]
**Describe the bug**
Configuration under `spring.cloud.consul.discovery.server-list-query-tags` property is ignored when quering service's instances while using Spring Cloud LoadBalancer.

**Sample**
When application has given configuration (which enables Spring LoadBalancer):
```
spring:
  cloud:
    consul:
      discovery:
        server-list-query-tags:
          <my-service-id>: leader
    loadbalancer:
      ribbon:
        enabled: false
```
there is expecting to load-balance requests between <my-service-id> instances only with `leader` tag, but this tag is ignored instead and requests are dispatched between all available instances.

In case of usage Ribbon (`spring.loadbalancer.ribbon.enabled=true`) above issue does not occur.
