### ISSUE TITLE
ConfigDataResourceNotFoundException not handled

### ISSUE THREAD

**Issue by aoudiamoncef** [spring-cloud/spring-cloud-consul#693]
Hi,

application.yml:

```yml
spring:
  config:
    import: "consul:${spring.cloud.consul.host}:${spring.cloud.consul.port}/dev"
```

Consul:
```console
curl -XPUT --data-binary @application.yml http://127.0.0.1:8500/v1/kv/my-api/dev.yml
```

At startup, I got:
```log
***************************
APPLICATION FAILED TO START
***************************

Description:

Config data resource '[ConsulConfigDataResource@714e7fd5 context = '/dev.properties', optional = false, properties = [ConsulConfigProperties@38fe6b0d enabled = true, prefix = 'my-api', defaultContext = 'application', profileSeparator = ',', format = FILES, dataKey = 'data', aclToken = [null], watch = [ConsulConfigProperties.Watch@6c3fd532 waitTime = 55, enabled = false, delay = 1000], failFast = true, name = 'adp-api-s']]' via location 'consul:localhost:8500/dev' does not exist

Action:

Check that the value 'consul:localhost:8500/dev' at class path resource [application.yaml] - 96:13 is correct, or prefix it with 'optional:'
```

Workaround:
```console
curl -XPUT --data-binary @application.yml http://127.0.0.1:8500/v1/kv/my-api/dev.yml
curl -XPUT --data-binary @application.yaml http://127.0.0.1:8500/v1/kv/my-api/dev.yaml
curl -XPUT --data-binary @application.properties http://127.0.0.1:8500/v1/kv/my-api/dev.properties
```

I tried another configuration without success:
```yml
  config:
    import: "optional:consul:${spring.cloud.consul.host}:${spring.cloud.consul.port}/dev"
    on-not-found: ignore
```

Related to issue #692

Thanks
