### ISSUE TITLE
Removal of "tags as metadata" breaks my gateway include expression

### ISSUE THREAD

**Issue by lucasoares** [spring-cloud/spring-cloud-consul#698]
Hello.

[This commit](https://github.com/bono007/spring-cloud-consul/commit/c3f23675499ca74b6a716bc61b733d14824fea39#diff-2a667f48e0dcb665886b85796597ff947f181bba055c1216d573b68cb3764a8c) removed the ability to use tags as metadata with Consul.

I have more than thousand services registered using tags and my Spring Cloud Gateway have a custom `include-expression`:
```yaml
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          include-expression: metadata[prefix] != null and metadata[service_name] != null and metadata[service_host] != null and metadata[service_port] != null and metadata[service_host] != 'custom_host'
```

With new Spring Cloud Gateway now this expression always results in a empty list.
I didn't found any documentation on how to workaround this without having to re-deploy my entire service architecture to register metadata instead tags.

What to do? Is there any documentation about breaking changes on Consul discovery service that I can know about these changes?

I really need a workaround since I can't add metadata on all my services right now.

Sorry if this is the wrong project to create this issue. If so please inform me so I can move it to Spring Cloud Gateway. Thanks
