### ISSUE TITLE
bootstrap.yml consul Config is unavailable

### ISSUE THREAD

**Issue by jf11480** [spring-cloud/spring-cloud-consul#720]
**Describe the bug**
Please provide details of the problem, including the version of Spring Cloud that you
are using. 

```xml
		<!-- https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-dependencies -->
		<spring-boot-dependencies.version>2.4.5</spring-boot-dependencies.version>

		<!-- https://mvnrepository.com/artifact/org.springframework.cloud/spring-cloud-dependencies -->
		<spring-cloud-dependencies.version>2020.0.2</spring-cloud-dependencies.version>

```

**Sample**
If possible, please provide a test case or sample application that reproduces
the problem. This makes it much easier for us to diagnose the problem and to verify that
we have fixed it.

application.yml  is available
```yml
spring: 
  config:
    import: optional:consul:qolome-server:8500
  application:
    name: cloud-collector
  cloud:
    consul:
      discovery:
      config: # 配置中心设置   
        enabled: true # 启用配置中心
        prefixes:
        - configuration
        format: yaml # YML格式文件
        data-key: data # 为应用配置的key名字，值为整个应用配置的字符串。
        profile-separator: ':' # 环境分隔符，默认值 ","
        default-context: cloud-common-config # 默认加载配置
        watch:
          enabled: true # 启用配置自动刷新
          wait-time: 1 # 请求 consul api 的延迟，单位：秒
          delay: 10000 # 刷新频率，单位：毫秒
```

bootstrap.yml is unavailable
```yml

spring: 
  config:
    import: optional:consul:qolome-server:8500
  application:
    name: cloud-collector
  cloud:
    consul:
      discovery:
      config: # 配置中心设置   
        enabled: true # 启用配置中心
        prefixes:
        - configuration
        format: yaml # YML格式文件
        data-key: data # 为应用配置的key名字，值为整个应用配置的字符串。
        profile-separator: ':' # 环境分隔符，默认值 ","
        default-context: cloud-common-config # 默认加载配置
        watch:
          enabled: true # 启用配置自动刷新
          wait-time: 1 # 请求 consul api 的延迟，单位：秒
          delay: 10000 # 刷新频率，单位：毫秒
```
