### ISSUE TITLE
Cannot load application with consul as config center

### ISSUE THREAD

**Issue by lllvantis** [spring-cloud/spring-cloud-consul#724]
**Describe the bug**
I'm trying to launch an app with consul as a config center, but it failed with the error:
File extension is not known to any PropertySourceLoader.

BTW the properties has been loaded successfully due to my log but the app failed to launch.

**Sample**
application.yml:

```
spring:
  application:
    name:
      vochat-gateway
  cloud:
    consul:
      config:
        format: yaml
```

with JAVA_OPTS=-Dspring.config.import=consul:
