### ISSUE TITLE
Discovery service properties naming

### ISSUE THREAD

**Issue by jmnarloch** [spring-cloud/spring-cloud-consul#74]
This is a minor issue, although the discovery service naming seems inconsistent, Eureka uses it's own root 'eureka': eureka.client.serviceUrl, while consul is under spring.cloud.consul, ie.:

```
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
```

```
spring:
  cloud:
    consul:
      host: localhost
      port: 8500
```
