### ISSUE TITLE
How to configure TLS for consul client

### ISSUE THREAD

**Issue by rola0411** [spring-cloud/spring-cloud-consul#754]
```yml
spring:
  application:
    name: demo-one
  cloud:
    consul:
      host: ${CONSUL_CLIENT_IP:10.18.7.3} 
      port: ${CONSUL_CLIENT_PORT:8501}
      discovery:
        enabled: true
        register: false 
        deregister: true
        acl-token: ${ACL_TOKEN:334475b6-41e7-0453-eb36-be7144703481}
      tls:
        certificate-path: e:\consul-client-ca.pem
        certificate-password: ？？？
        key-store-instance-type: ？？？
        key-store-password: ？？？
        key-store-path: ？？？
      scheme: HTTPS

```

hi ，I used service mesh ，I exported the CA certificate. and I got the xxx-ca.pem and xxx-ca-key.pem,
now, I don`t know how to set them。

Could U tell me。。。。thank you
