### ISSUE TITLE
ACL token is not used when importing externalized configuration

### ISSUE THREAD

**Issue by onyn** [spring-cloud/spring-cloud-consul#768]
My spring boot application extensively use [externalized configuration](https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.external-config) feature. Configuration stored in:

1. bootstrap.yml
2. application.yml
3. SPRING_APPLICATION_JSON environment variable (only in production)
4. Consul KV

Since boot 2.4 bootstrap.yml is deprecated. So I update my application for using new [spring.config.import](https://docs.spring.io/spring-cloud-consul/docs/4.0.0-M1/reference/html/#config-data-import) configuration option.

My updated configuration:
<details>
  <summary>application.yml</summary>

```yaml
spring:
  application:
    name: myapp
  cloud:
    # Consul integration initially disabled for easier local development.
    # On production consul enabled with SPRING_APPLICATION_JSON.
    consul:
      enabled: false
      config:
        enabled: false
        format: YAML
  config:
    import: "consul:"
```
</details>

<details>
  <summary>SPRING_APPLICATION_JSON</summary>

```json
{
  "spring": {
    "cloud": {
      "consul": {
        "enabled": true,
        "token": "2b8d6819-0fb2-4e4f-b80c-bf24f922277b",
        "host": "192.168.23.3",
        "config": {
          "enabled": true
        }
      }
    }
  }
}
```
</details>

This configuration doesn't work. Configuration from consul not imported.

After some debugging I found that ACL token is not used for import process. My consul have ACL configured and returns _404 Not Found_ for kv requests without ACL token. I figured it out via tcpdump:

<details>
  <summary>http dump</summary>

This request originates from spring application

```http
GET /v1/kv/config/myapp,default/?recurse HTTP/1.1
Host: 192.168.23.3:8500
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.13 (Java/17)
Accept-Encoding: gzip,deflate

HTTP/1.1 404 Not Found
Vary: Accept-Encoding
X-Consul-Default-Acl-Policy: deny
X-Consul-Index: 12017234
X-Consul-Knownleader: true
X-Consul-Lastcontact: 0
X-Consul-Query-Backend: blocking-query
Date: Thu, 10 Feb 2022 13:12:54 GMT
Content-Length: 0
```
</details>

Also I confirmed this by inspecting ConsulConfigProperties object during config loading phase:

<details>
  <summary>screenshot</summary>

![image](https://user-images.githubusercontent.com/329168/153427498-5d356b77-9e9b-4d67-aeb5-9f58c3dde647.png)
</details>

[Complete, minimal, verifiable sample](https://github.com/onyn/spring-cloud-consul-768).
