### ISSUE TITLE
Support multiple file names in data-key for YML format

### ISSUE THREAD

**Issue by bpeterson3134** [spring-cloud/spring-cloud-consul#835]
**Is your feature request related to a problem? Please describe.**
I'm trying to use spring-cloud consul (v4.0.4) to read properties from multiple yaml files with the same prefix. However data-key, only accepts a single file name.

**Describe the solution you'd like**
So say I have below config files I want to have consul manage and refresh using config watcher:

```
src/main/resources/application.yml
src/main/resources/application-dev.yml
src/main/resources/features/features.yml
src/main/resources/mappings/my-mappings-dev.yml
```

I want to provide a config like this:

```
spring:
  config:
    import: "optional:consul:"
  cloud:
    consul:
      discovery:
        enabled: ${features.config-client.${environment}.enabled}
      enabled: ${features.config-client.${environment}.enabled}
      scheme: https
      host: ${consul_host}
      port: 443
      config:
        fail-fast: true
        acl-token: ${consul_token}
        enabled: ${features.config-client.${environment}.enabled}
        default-context: dev
        prefixes:
          - my/custom/path
        format: YAML
        data-key: application.yml,application-dev.yml,features.yml,my-mappings-dev.yml 
        watch:
          enabled: ${features.config-client.${environment}.enabled}
          delay: 300000
          wait-time: 5
          
```
          
 
Another option that would work for me is if I reference one file like application-dev.yml and use spring.config.import to import the other ones, then consul would refresh all 4 files even though data-key is set to application-dev.yml. However, Im thinking the first solution would maybe provide more flexibility?

**Describe alternatives you've considered**
I've just been considering consul for externalizing multiple configs although it seems it only supports a single externalized config. Im unable to use different key prefixes for each file because the way things work from within our company is that a single github repository is onboarded and given a single prefix. Then I can onboard multiple files for that prefix/repository. Then anytime a file is changed in github and webhook is sent to consul server to update the properties in consul for the changes (now github and consul are in sync). Everything works fine for each individual file, but unable to get multiple files to be read and refreshed using consul. One of the reasons is for this snippet of code in ConsulPropertySource:

``` 
protected void parsePropertiesWithNonKeyValueFormat(List<GetValue> values, ConsulConfigProperties.Format format) {
        if (values != null) {
            Iterator var3 = values.iterator();

            while(var3.hasNext()) {
                GetValue getValue = (GetValue)var3.next();
                String key = getValue.getKey().replace(this.context, "");
                if (this.configProperties.getDataKey().equals(key)) {
                    this.parseValue(getValue, format);
                }
            }

        }
    }
```

**Additional context**
